### ISSUE TITLE
[ODC] - Get Page Source - The driver is failing with a 500 fetch error

### ISSUE THREAD

**Issue by semeguze** [dlenroc/appium-roku-driver#100]
### Issue Summary

I’m encountering an internal error when running a command with the RokuDriver and the ODC context. The error message indicates a `TypeError: fetch failed.`

I'm using the most updated Node + Appium + Appium inspector versions.

### Context and Additional Information

We are trying to use the ODC context instead of ECP because our team is attempting to add custom arguments to the DOM file, such as the `automationID`. However, we are not able to view the automationID argument while reading the DOM file with the default configuration.

### Capabilities used:

```json
{
  "platformName": "roku",
  "appium:automationName": "roku",
  "appium:app": "/Users/sebastian.mesa/Downloads/redacted.zip",
  "appium:ip": "192.168.2.125",
  "appium:password": "rokupass",
  "appium:context": "ODC"
}
``` 

### Steps to Reproduce

- Set up the RokuDriver with the above capabilities.
- Start a Appium Inspector session using those caps.
- Observe the error in the server terminal: `TypeError: fetch failed.`

The session is starting using the Appium Inspector, and the App is installed in my Roku device, but the page source it's not loading:

<img width="1106" alt="image" src="https://github.com/dlenroc/appium-roku-driver/assets/30412804/b0a6e090-3389-4c02-9d77-3c0a479888a1">

### What did I already try?

I already tried:
- To update the node_modules libraries 
- Updating npm/node
- Installing `npm install node-fetch` both locally and globally without success

### System info

```bash
echo "macOS Version:" && sw_vers && echo "" && echo "Node.js Version:" && node -v && echo "" && echo "npm Version:" && npm -v && echo "" && (command -v nvm > /dev/null 2>&1 && echo "nvm Version:" && nvm --version && echo "" || true) && (command -v appium > /dev/null 2>&1 && echo "Appium Version:" && appium -v && echo "" || true) && echo "Global npm Packages:" && npm list -g --depth=0 && echo "" && (command -v java > /dev/null 2>&1 && echo "Java Version:" && java -version && echo "" || true) && (command -v python > /dev/null 2>&1 && echo "Python Version:" && python --version && echo "" || true) && (command -v ruby > /dev/null 2>&1 && echo "Ruby Version:" && ruby -v && echo "" || true)
macOS Version:
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

Node.js Version:
v22.3.0

npm Version:
10.8.1

nvm Version:
0.34.0

Appium Version:
2.10.3

Global npm Packages:
/Users/sebastian.mesa/.nvm/versions/node/v22.3.0/lib
├── appium-doctor@1.16.2
├── appium@2.10.3
├── corepack@0.28.2
├── node-fetch@3.3.2
├── npm@10.8.1
└── run-script-os@1.1.6


Java Version:
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-11.0.17.8.1 (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.17.8.1 (build 11.0.17+8-LTS, mixed mode)

Ruby Version:
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]

``` 

### Logs

These are the logs from the `appium` server:

```bash
node -v
npm -v
appium
v22.3.0
10.8.1
[Appium] Welcome to Appium v2.10.3 (REV 3d9c31d94488884e74ae1ba0d46bc6607bc74667)
[Appium] The autodetected Appium home path: /Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver
[Appium] Attempting to load driver roku...
[Appium] Requiring driver at /Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver/dist/index.js
[Appium] RokuDriver has been successfully loaded in 0.419s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
	http://127.0.0.1:4723/ (only accessible from the same host)
	http://192.168.2.245:4723/
[Appium] Available drivers:
[Appium]   - roku@0.12.0 (automationName 'roku')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session {"capabilities":{"alwaysMatch":{"platformName":"roku","appium:automationName":"roku","appium:app":"/Users/sebastian.mesa/Downloads/redacted.zip","appium:ip":"192.168.2.125","appium:password":"rokupass","appium:context":"ODC","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"roku","appium:automationName":"roku","appium:app":"/Users/sebastian.mesa/Downloads/redacted.zip","appium:ip":"192.168.2.125","appium:password":"rokupass","appium:context":"ODC","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@1c55] Calling AppiumDriver.createSession() with args: [{"platformName":"roku","appium:automationName":"roku","appium:app":"/Users/sebastian.mesa/Downloads/redacted.zip","appium:ip":"192.168.2.125","appium:password":"rokupass","appium:context":"ODC","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"roku","appium:automationName":"roku","appium:app":"/Users/sebastian.mesa/Downloads/redacted.zip","appium:ip":"192.168.2.125","appium:password":"rokupass","appium:context":"ODC","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@1c55] Event 'newSessionRequested' logged at 1718987480638 (11:31:20 GMT-0500 (Colombia Standard Time))
[Appium] Attempting to find matching driver for automationName 'roku' and platformName 'roku'
[Appium] The 'roku' driver was installed and matched caps.
[Appium] Will require it at /Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver
[Appium] Requiring driver at /Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver/dist/index.js
[AppiumDriver@1c55] Appium v2.10.3 creating new RokuDriver (v0.12.0) session
[AppiumDriver@1c55] Checking BaseDriver versions for Appium and RokuDriver
[AppiumDriver@1c55] Appium's BaseDriver version is 9.10.3
[AppiumDriver@1c55] RokuDriver's BaseDriver version is 9.10.3
[RokuDriver@355a] undefined
[RokuDriver@355a] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "roku",
    "appium:automationName": "roku",
    "appium:app": "/Users/sebastian.mesa/Downloads/redacted.zip",
    "appium:ip": "192.168.2.125",
    "appium:password": "rokupass",
    "appium:context": "ODC",
    "appium:newCommandTimeout": 3600,
    "appium:connectHardwareKeyboard": true
  },
  "firstMatch": [
    {}
  ]
}
[RokuDriver@355a] The following provided capabilities were not recognized by this driver:
[RokuDriver@355a]   connectHardwareKeyboard
[RokuDriver@355a] Session created with session id: 404ef6d4-4bdc-4e7f-8fe5-541aad23a532
[BaseDriver] Using local app '/Users/sebastian.mesa/Downloads/redacted.zip'
[RokuDriver@355a] Channel is already installed
[AppiumDriver@1c55] New RokuDriver session created successfully, session 404ef6d4-4bdc-4e7f-8fe5-541aad23a532 added to master session list
[AppiumDriver@1c55] Event 'newSessionStarted' logged at 1718987483732 (11:31:23 GMT-0500 (Colombia Standard Time))
[RokuDriver@355a] Cached the protocol value 'W3C' for the new session 404ef6d4-4bdc-4e7f-8fe5-541aad23a532
[RokuDriver@355a] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"roku","automationName":"roku","app":"/Users/sebastian.mesa/Downloads/redacted.zip","ip":"192.168.2.125","password":"rokupass","context":"ODC","newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[HTTP] <-- POST /session 200 3129 ms - 432
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/screenshot {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getScreenshot() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getScreenshot() result: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCALQBQADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5/ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC...
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/screenshot 200 1136 ms - 28480
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/window/rect {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getWindowRect() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
    at RokuDriver.executeCommand (/Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver/node_modules/@appium/base-driver/lib/basedriver/driver.ts:100:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/window/rect 405 21 ms - 406
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/source {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getPageSource() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Encountered internal error running command: TypeError: fetch failed
    at node:internal/deps/undici/undici:13193:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at execute (file:///Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver/node_modules/@dlenroc/roku-odc/src/internal/execute.ts:45:20)
    at getAppUI (file:///Users/sebastian.mesa/.appium/node_modules/@dlenroc/appium-roku-driver/node_modules/@dlenroc/roku-odc/src/commands/getAppUI.ts:10:20)
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/source 500 23 ms - 600
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 200 7 ms - 42
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 3 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 6 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 26 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 6 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 13 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 6 ms - -
[404ef6d4][HTTP] --> GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts {}
[404ef6d4][RokuDriver@355a] Calling AppiumDriver.getTimeouts() with args: ["404ef6d4-4bdc-4e7f-8fe5-541aad23a532"]
[404ef6d4][RokuDriver@355a] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[404ef6d4][HTTP] <-- GET /session/404ef6d4-4bdc-4e7f-8fe5-541aad23a532/timeouts 304 6 ms - -

``` 

Any help would be really appreciated!!
Thanks! 🚀

**Comment by dlenroc** [comment]
Hi @semeguze, could you please confirm if the ODC server injected into your application by the driver is functioning correctly?

- Check the Roku BrightScript logs while performing the steps mentioned:
   ```bash
   nc <device-ip> 8085 # for Linux/Mac
   telnet <device-ip> 8085 # for Windows
   ```
   📝 This may reveal app instrumentation issues.

- After installing and running the application using Automation/Inspector + Roku Driver, execute the following requests:
   ```bash
   curl http://<device-ip>:8061/registry  # Registry state
   curl http://<device-ip>:8061/app-ui    # XML Page source
   ```
   📝 This will indicate if the ODC server launches with the app and whether the issue pertains to the page source or the entire server. Please review BrightScript logs during these requests as well.

**Comment by semeguze** [comment]
Thanks for your response!!!
I'm sorry for the late reply, I was a bit busy with other endeavors!

---

Regarding:
```shell
nc <device-ip> 8085
```

It's working fine, and listening to logs ✅ 

---

```shell
curl http://<device-ip>:8061/registry
```

Returns the App registry as expected with the app values ✅ 

<img width="1653" alt="image" src="https://github.com/dlenroc/appium-roku-driver/assets/30412804/c98852a4-f071-480b-bc1e-e86ad2a37719">

---

```shell
curl http://<device-ip>:8061/app-ui
```

This one is giving an error! 🤔 

The endpoint is infinitely loading, but if I take a look to the logs, it's generating a crash!

```shell
BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.

Suspending threads...
[...]
Thread selected:  1*   ...ialization/toSerializable.brs(20)       for each item in source.items()

Current Function:
012:      end for
013:
014:      return results
015:    end if
016:
017:    if getInterface(source, "ifAssociativeArray") <> invalid
018:      result = {}
019:
020:*     for each item in source.items()
021:        value = item.value
022:
023:        if getInterface(value, "ifSGNodeField") <> invalid
024:          value = value.getField("id")
Source Digest(s):
pkg:                       dev   0.00.0 00000000 Redacted App | 000000000000REDACTED000000000000

[...]

Function Call Operator ( ) attempted on non-function. (runtime error &he0) in pkg:/components/odc/helpers/serialization/toSerializable.brs(20)
Backtrace:
#9  Function odc_toserializable(source As Object) As Object
   file/line: pkg:/components/odc/helpers/serialization/toSerializable.brs(20)
#8  Function odc_toserializable(source As Object) As Object
   file/line: pkg:/components/odc/helpers/serialization/toSerializable.brs(27)
#7  Function odc_toserializable(source As Object) As Object
   file/line: pkg:/components/odc/helpers/serialization/toSerializable.brs(11)
#6  Function odc_toserializable(source As Object) As Object
   file/line: pkg:/components/odc/helpers/serialization/toSerializable.brs(27)
#5  Function odc_toserializable(source As Object) As Object
   file/line: pkg:/components/odc/helpers/serialization/toSerializable.brs(27)
#4  Function $anon_6a2(target As Object, node As Object, fieldkey As String) As Void
   file/line: pkg:/components/odc/helpers/serialization/toXML.brs(79)
#3  Function $anon_6a1(target As Object, node As Object) As Void
   file/line: pkg:/components/odc/helpers/serialization/toXML.brs(30)
#2  Function $anon_6a0(target As Object, node As Object) As Void
   file/line: pkg:/components/odc/helpers/serialization/toXML.brs(12)
#1  Function odc_toxml(source As Object, fields As Object) As String
   file/line: pkg:/components/odc/helpers/serialization/toXML.brs(89)
#0  Function odc_getappui(fields As Object) As String
   file/line: pkg:/components/odc/client.brs(4)
Local Variables:
source           roAssociativeArray refcnt=4 count:1
global           Interface:ifGlobal
m                roAssociativeArray refcnt=8 count:48
results          <uninitialized>
index            <uninitialized>
result           roAssociativeArray refcnt=1 count:0
item             <uninitialized>
value            <uninitialized>
Threads:
ID    Location                                Source Code
 0    pkg:/source/index.brs(69)                 msg = wait(300000, gaa.mainPort)
 1*   ...ialization/toSerializable.brs(20)       for each item in source.items()
 
 [...]
```

_Using `[...]` to avoid sharing some extra data._

@dlenroc thanks for your help! 🙂

**Comment by dlenroc** [comment]
A fix for this issue was implemented via https://github.com/dlenroc/node-roku/pull/112 and released as [@dlenroc/roku-odc@2.1.1](https://www.npmjs.com/package/@dlenroc/roku-odc/v/2.1.1).

Could you please try reinstalling the Roku driver in Appium and check if the issue is resolved?

```sh
appium driver uninstall roku
appium driver install --source npm @dlenroc/appium-roku-driver
```

**Comment by semeguze** [comment]
Thanks for the fix!! 🙌 

Looks like that's fixed, but now there's another crash:

```bash
BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.

Suspending threads...
Thread selected:  1*   ...lpers/serialization/toXML.brs(91)     return xml.genXML(false)

Current Function:
083:            target.addAttribute(fieldKey, odc_toString(fieldValue))
084:          end if
085:        end if
086:      end sub
086:
087:    }
088:
089:    scope.render(xml, source)
090:
091:*   return xml.genXML(false)
092:  end function
Source Digest(s):
[...]

Execution timeout (runtime error &h23) in pkg:/components/odc/helpers/serialization/toXML.brs(91)
Backtrace:
#1  Function odc_toxml(source As Object, fields As Object) As String
   file/line: pkg:/components/odc/helpers/serialization/toXML.brs(91)
#0  Function odc_getappui(fields As Object) As String
   file/line: pkg:/components/odc/client.brs(4)
Local Variables:
source           roSGNode:MainScene refcnt=1
fields           roInvalid refcnt=3
global           Interface:ifGlobal
m                roAssociativeArray refcnt=3 count:52
xml              roXMLElement refcnt=1
scope            roAssociativeArray refcnt=1 count:4
Threads:
ID    Location                                Source Code
 0    pkg:/source/index.brs(69)                 msg = wait(300000, gaa.mainPort)
[...]
```

**Comment by dlenroc** [comment]
Thanks for letting me know. Fixing that is challenging because it's related to the timeout Roku imposes on the render thread. I'll explore ways to speed it up tomorrow.

You could try restarting the app to check if the issue persists when requesting only the attributes you're interested in:

```
http://<device-ip>:8061/app-ui?fields={"*":["id", "automationID"]}
```

> If this approach works, you can specify which attributes should be returned by the `getPageSource` command using the `appium:settings` capability:
> ```json
 > { "appium:settings[elementResponseAttributes]": "automationID,id,uri,selected,visible,focused,text,bounds,DynamicKeyGrid/keyFocused" }
> ```

**Comment by semeguze** [comment]
Well, that worked!! thanks a lot 🙌 

![image](https://github.com/dlenroc/appium-roku-driver/assets/30412804/d91e8523-ddf6-4f04-9e00-2664ac2d6d00)

I will investigate a bit more about how we can implement this in our team, thanks!

**Comment by semeguze** [comment]
Also one last question, do you know if it's possible to also get the automationID value, using the default ECP context? - Thanks!

**Comment by dlenroc** [comment]
Unfortunately, I'm not aware of any way to retrieve an app representation containing custom attributes through the ECP API 😢
